[package]
name = "sara-lang"
version = "0.1.0"
authors = ["Mark Cohen <m@mpc.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
strum = "0.20"
strum_macros = "0.20"
unicase = "2.6.0"